version: 2
jobs:
  build:
    docker: # run the steps with Docker
      - image: docker:17.05.0-ce-git # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands
      - checkout
      - run: npm install
      - run: ./build.sh

  test:
    docker: # run the steps with Docker
      - image: docker:17.05.0-ce-git # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands
      - checkout
      - run: npm install
      - run: npm test
#      - run: sudo service docker start
#      - run: docker images
#      - run: docker build . --tag samgreaves/rustrestapi
#      - run: docker images

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
      requires:
        - build