version: 2
jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/node:dubnium-alpine # ...with this image as the primary container; this is where all `steps` will run
      - image: mongo:3.4.4 # and this image as the secondary service container
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: cucumber
          command: 'sudo npm install cucumber@1.3.3'
      - run: # run tests
          name: test
          command: npm test
