version: 2
jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/node:11.6.0 # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: npm install
      - run: ./build.sh

  test:
    docker: # run the steps with Docker
      - image: circleci/node:11.6.0 # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands
      - setup_remote_docker:
                docker_layer_caching: true
      - checkout
      - run: npm install
      - run: npm test

  package:
    docker: # run the steps with Docker
      - image: circleci/node:11.6.0 # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands
      - setup_remote_docker:
                docker_layer_caching: true
      - checkout
      - run: npm install

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t   $DOCKER_REPO/$DOCKER_IMAGENAME:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push $DOCKER_REPO/$DOCKER_IMAGENAME:$TAG

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test
    - package:
      type: approval
      requires:
        - build
        - test