version: 2
jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/node:11.6.0 # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: npm install
      - run: ./build.sh

  test:
    docker: # run the steps with Docker
      - image: circleci/node:11.6.0 # ...with this image as the primary container; this is where all `steps` will run
      - image: mongo:3.4.4

    steps: # a collection of executable commands
      - setup_remote_docker:
                docker_layer_caching: true
      - checkout
      - run: npm install
      - run: npm test

  package:
    docker: # run the steps with Docker
      - image: circleci/node:11.6.0 # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands
      - setup_remote_docker:
                docker_layer_caching: true
      - checkout
      - run: npm install

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t   $DOCKER_REPO/$DOCKER_IMAGENAME:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push $DOCKER_REPO/$DOCKER_IMAGENAME:$TAG

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
        requires:
          - build
    - approve:
        type: approval
        filters:
          branches:
            only:
              - master
        requires:
          - test
    - package:
        filters:
          branches:
            only:
              - master
        requires:
          - approve